module DfE
  module ReferenceData
    module InternationalQualifications
      SCHEMA = {
        id: :string,
        country: :string,
        country_code: { kind: :code, pattern: %r{^([a-z]{2,3}|n/a)$} },
        qualification_name: :string,
        qualification_group: :symbol,
        enic_band: { kind: :optional, schema: :string },
        rqf_level: { kind: :optional, schema: :string },
        enic_notes: { kind: :optional, schema: :string },
        equivalence_type: { kind: :optional, schema: :string },
        grades: { kind: :array, element_schema: :string },
        gcse_equivalent_grades: { kind: :array, element_schema: :string }
      }.freeze

      LIST =
        {
          '9450f8ea-cc70-4af1-92df-f848f03aa4ff' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'gaokao (national college entrance exam)',
            qualification_group: :gaokao,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            enic_notes: 'university entry',
            equivalence_type: 'a_level',
            grades: ['good', 'top tier', 'borderline', 'high', 'pass', 'fail'],
            gcse_equivalent_grades: ['good', 'top tier', 'high', 'pass'] },
          '10139d58-e2ab-418a-bfcc-f5057612cfa4' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'benke (bachelor\'s degree)',
            qualification_group: :degree,
            enic_band: 'band 10',
            rqf_level: 'level_6',
            equivalence_type: 'degree',
            grades: ['pass', 'youxiu (excellent)', 'good'] },
          '62b04aee-3e00-413c-af14-f57c6a72ef02' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'boshi (doctorate)',
            qualification_group: :degree,
            enic_band: 'band 15',
            rqf_level: 'level_8',
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '7c2505aa-c22b-4988-8e38-6242d860bb94' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'secondary vocational school diploma',
            qualification_group: :vocational_diploma,
            enic_band: 'band 6–7',
            rqf_level: 'level_3–4',
            enic_notes: 'programme-dependent',
            grades: ['pass', 'excellent', 'good'] },
          'b20d1ddd-0eed-4232-b00d-4ec612454526' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'senior secondary school graduation',
            qualification_group: :high_school_diploma,
            enic_notes: 'huikao is the exam',
            equivalence_type: 'gcse',
            grades: ['e', '90', '70', 'f', '60', 'd', '80', 'a', 'b', 'c'],
            gcse_equivalent_grades: ['90', '70', '60', '80', 'a', 'b', 'c'] },
          '7d3bb4b2-8a3e-4afa-9b86-296b5b102fce' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'shuoshi (master\'s degree)',
            qualification_group: :degree,
            enic_band: 'band 11',
            rqf_level: 'level_7',
            equivalence_type: 'degree',
            grades: ['good', 'awarded', 'pass', 'youxiu'] },
          '1b0e533a-f9de-4659-8166-fe43b3f9b891' =>
          { country: 'china',
            country_code: 'cn',
            qualification_name: 'zhongkao (senior high entrance exam)',
            qualification_group: :zhongkao,
            enic_band: 'band 2',
            rqf_level: 'level_1–2',
            enic_notes: 'entrance to senior high',
            equivalence_type: 'less_than_gcse',
            grades: ['fail', 'good', 'pass', 'excellent'] },
          '88d78350-cadf-45d4-85f4-9f228d1b77dc' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'baccalauréat (général/technologique/professionnel)',
            qualification_group: :baccalaureat,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            enic_notes: 'baccalauréat',
            equivalence_type: 'a_level',
            grades: ['passable', 'bien', 'ajourné', 'très bien', 'assez bien'],
            gcse_equivalent_grades: ['passable', 'bien', 'très bien', 'assez bien'] },
          '10db21f2-626e-4f36-b051-171de804f917' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'brevet d\'études professionnelles (bep)',
            qualification_group: :bep,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            enic_notes: 'historical award',
            equivalence_type: 'vocational_level_2',
            grades: ['très bien', 'passable', 'assez bien', 'bien'] },
          '7b82dbdd-ec28-4b24-a422-9145393350cc' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'brevet de technicien supérieur (bts)',
            qualification_group: :bts,
            enic_band: 'band 8',
            rqf_level: 'level_5',
            enic_notes: 'two-year post-bac',
            equivalence_type: 'vocational_level_5',
            grades: ['passable', 'bien', 'assez bien'] },
          '02e40bb9-8e50-4fea-a09e-9a4695370d99' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'certificat d\'aptitude professionnelle (cap)',
            qualification_group: :cap,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            enic_notes: 'initial vocational',
            equivalence_type: 'vocational_level_2',
            grades: ['très bien', 'assez bien', 'passable', 'bien'] },
          '8408637f-31d5-402c-9ebd-4d57463a3a53' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'diplôme national du brevet (dnb)',
            qualification_group: :dnb,
            enic_band: 'band 2',
            rqf_level: 'level_1–2',
            enic_notes: 'brevet des collèges',
            equivalence_type: 'gcse',
            grades: ['insuffisant', 'très bien', 'passable', 'assez bien', 'bien'],
            gcse_equivalent_grades: ['très bien', 'passable', 'assez bien', 'bien'] },
          'a636d5cb-0057-4781-b7f0-7aca744949d5' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'doctorat',
            qualification_group: :degree,
            enic_band: 'band 15',
            rqf_level: 'level_8',
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '211f8a2f-102e-4a0d-9f2b-dd2be8435c86' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'licence (bachelor\'s degree)',
            qualification_group: :degree,
            enic_band: 'band 10',
            rqf_level: 'level_6',
            equivalence_type: 'degree',
            grades: ['bien', 'passable', 'très bien', 'assez bien'] },
          '1e9da793-4d57-4283-bef8-54ac5e2d44e9' =>
          { country: 'france',
            country_code: 'fr',
            qualification_name: 'master',
            qualification_group: :degree,
            enic_band: 'band 11',
            rqf_level: 'level_7',
            equivalence_type: 'degree',
            grades: ['passable', 'très bien', 'bien', 'awarded'] },
          'f90797a4-190d-47de-8baa-105cc6d9a99f' =>
          { country: 'ghana',
            country_code: 'gh',
            qualification_name: 'bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['pass', 'second class upper', 'second class lower', 'third class', 'first class'] },
          '25f4a17a-20ed-43ce-bab4-0d2472f4a460' =>
          { country: 'ghana',
            country_code: 'gh',
            qualification_name: 'basic education certificate examination (bece)',
            qualification_group: :bece,
            equivalence_type: 'less_that_gcse',
            grades: ['grade 6', 'grade 1', 'grade 3', 'grade 9', 'grade 2', 'grade 8', 'grade 7'] },
          '2733d738-b644-472b-9ba0-929a17a1c85b' =>
          { country: 'ghana',
            country_code: 'gh',
            qualification_name: 'doctorate',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '64dc5679-d02d-4e14-a7f6-4e8bb70c0cd8' =>
          { country: 'ghana',
            country_code: 'gh',
            qualification_name: 'higher national diploma (hnd)',
            qualification_group: :diploma,
            enic_band: 'band 8',
            rqf_level: 'level_5',
            equivalence_type: 'diploma',
            grades: ['lower credit', 'upper credit', 'distinction'] },
          '94a4f518-0f73-4fb7-a3d9-e8e8b406411b' =>
          { country: 'ghana',
            country_code: 'gh',
            qualification_name: 'master\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['pass', 'awarded', 'distinction', 'merit'] },
          '00dd1e0b-8508-4ceb-b93f-a8810aa30178' =>
          { country: 'ghana',
            country_code: 'gh',
            qualification_name: 'west african senior school certificate examination (wassce)',
            qualification_group: :wassce,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            enic_notes: 'ghana (wassce): a1–b3 = strong pass; c4–c6 = standard pass;',
            equivalence_type: 'gcse',
            grades: ['c4', 'b3', 'a1', 'b2', 'c5', 'c6', 'd7', 'e8'],
            gcse_equivalent_grades: ['c4', 'b3', 'a1', 'b2', 'c5', 'c6'] },
          '275c136a-b100-482c-af3a-3088150c876e' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['third class / pass', 'high second class', 'first class with distinction/first class', 'second class', 'pass'] },
          'b4ecbc32-af83-43bc-a546-aaeee6c5d24a' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'central board of secondary education (cbse)',
            qualification_group: :cbse,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            equivalence_type: 'gcse',
            grades: ['c1', 'e', 'a1', 'a2', 'c2', 'd', 'b1', 'b2'],
            gcse_equivalent_grades: ['c1', 'a1', 'a2', 'c2', 'b1', 'b2'] },
          'bf1ddf0b-ea54-4a3e-9990-9e2c250803f8' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'doctorate',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '3793c253-3508-48f5-8134-9f76ab207e5b' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'higher secondary certificate (hsc)',
            qualification_group: :hsc,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            equivalence_type: 'a_levels',
            grades: ['a2', '41', 'c1', 'c2', '81', 'a1', '71', 'b1', '51', '0', '61', 'e', 'd', '91', '33', 'b2'],
            gcse_equivalent_grades: ['a2', '41', 'c1', 'c2', '81', 'a1', '71', 'b1', '51', '61', '91', 'b2'] },
          'dc3030fc-67ed-42c3-8f5f-72c9eb9d83cf' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'indian certificate of secondary education (icse)',
            qualification_group: :icse,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            equivalence_type: 'gcse',
            grades: ['e', 'b1', 'c1', 'c2', 'a2', 'd', 'b2', 'a1'],
            gcse_equivalent_grades: ['b1', 'c1', 'c2', 'a2', 'b2', 'a1'] },
          'dc5d441a-d76a-49d6-a141-fd03653d040d' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'industrial training institute (iti) certificate',
            qualification_group: :iti_certificate,
            equivalence_type: 'iti_certificate',
            grades: ['first class', 'first class with distinction', 'pass', 'second class'] },
          '36a01ee1-f4df-4c1b-92bb-d3f5bd03ff34' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'master\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['merit', 'pass', 'awarded', 'distinction'] },
          '2ccb3491-49ca-4a3b-a12c-97a4ea6f69b9' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'polytechnic diploma',
            qualification_group: :polytechnic_diploma,
            enic_band: 'band 7',
            rqf_level: 'level_4',
            equivalence_type: 'polytechnic_diploma',
            grades: ['second class', 'pass', 'first class with distinction', 'first class'] },
          '2c2a13a9-b70d-4ec7-ae41-dce052e6c97b' =>
          { country: 'india',
            country_code: 'in',
            qualification_name: 'secondary school certificate (ssc)',
            qualification_group: :ssc,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            equivalence_type: 'gcse',
            grades: ['d', 'a2', 'e', 'b1', '41', 'c1', 'b2', 'a1', '71', 'c2', '51', '81', '61', '91', '33', '0'],
            gcse_equivalent_grades: ['a2', 'b1', '41', 'c1', 'b2', 'a1', '71', 'c2', '51', '81', '61', '91'] },
          '6eb7fd5e-d44b-44d9-b62f-59ad177d03c7' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'doctorate (phd/edd)',
            qualification_group: :degree,
            enic_band: 'band 15',
            rqf_level: 'level_8',
            equivalence_type: 'degree',
            grades: ['awarded'] },
          'c804b369-1391-40f2-a7f1-6f27b2063d52' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'honours bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['second class honours grade 1', 'first class honours', 'third class honours / pass', 'second class honours grade 2'] },
          '1fd9ca0a-d17c-4d0e-ae2d-4ce6cbb4b348' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'junior cycle (jc)',
            qualification_group: :junior_certificate,
            equivalence_type: 'less_that_gcse',
            grades: ['achieved', 'not graded / fail', 'higher merit', 'partially achieved', 'merit', 'distinction'] },
          '45382cb3-2641-4d2b-a366-9fdf0035a5ef' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'leaving certificate (lc) higher level',
            qualification_group: :leaving_certificate,
            equivalence_type: 'a_level',
            grades: ['h1', 'h3', 'h7', 'h2', 'h6', 'h5', 'h4', 'h8'],
            gcse_equivalent_grades: ['h1', 'h3', 'h2', 'h5', 'h4'] },
          '28bdd6b8-8eb9-40d4-a7d4-13e0da5bf75b' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'leaving certificate (lc) ordinary level',
            qualification_group: :leaving_certificate,
            equivalence_type: 'gcse',
            grades: ['o2', 'o4', 'o6', 'o5', 'o3', 'o7', 'o1'],
            gcse_equivalent_grades: ['o2', 'o4', 'o3', 'o1'] },
          'a650546a-2b2e-43ba-aba2-27b5124840f5' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'master\'s degree (research/mphil)',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '423da05e-d6be-423b-800f-c1f125048d03' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'master\'s degree (taught)',
            qualification_group: :degree,
            enic_band: 'band 11',
            rqf_level: 'level_7',
            equivalence_type: 'degree',
            grades: ['distinction', 'pass', 'merit'] },
          'fbf368ae-537f-45cd-9570-902ee2d0fdc1' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'ordinary bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['pass'] },
          '03816798-a833-4fff-a729-e73ecb1e8ec0' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'quality and qualifications ireland level 5 (qqi)',
            qualification_group: :quality_qualifications_ireland,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            equivalence_type: 'a_level',
            grades: ['distinction', 'merit', 'pass'],
            gcse_equivalent_grades: ['distinction', 'merit', 'pass'] },
          '076a248e-a254-4c16-8e83-a3c1b0c62173' =>
          { country: 'ireland',
            country_code: 'ie',
            qualification_name: 'quality and qualifications ireland level 6 (qqi)',
            qualification_group: :quality_qualifications_ireland,
            enic_band: 'band 7',
            rqf_level: 'level_4',
            equivalence_type: 'a_level',
            grades: ['merit', 'distinction', 'pass'],
            gcse_equivalent_grades: ['merit', 'distinction', 'pass'] },
          'b1cb8013-ad7b-406d-9546-2294b502bd14' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'diploma di maturità (liceo/it/ips)',
            qualification_group: :diploma_di_maturita,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            equivalence_type: 'a_level',
            grades: ['sufficiente', 'ottimo', 'honours (with distinction)', 'distinto', 'buono'],
            gcse_equivalent_grades: ['sufficiente', 'ottimo', 'honours (with distinction)', 'distinto', 'buono'] },
          '70b7502a-1de8-4a70-a53f-3088702c86b4' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'dottorato di ricerca (doctorate)',
            qualification_group: :degree,
            enic_band: 'band 15',
            rqf_level: 'level_8',
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '6f4ba059-3bee-4057-a2ba-3eaed3d60f07' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'istituto professionale (ips) diploma',
            qualification_group: :ips_diploma,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            enic_notes: 'istituto professionale diploma',
            equivalence_type: 'vocational_level_3',
            grades: ['sufficiente', 'ottimo', 'distinto', 'buono'] },
          '5b9ba2fc-5eeb-4117-8e95-b1bed2e3a067' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'istituto tecnico (it) diploma',
            qualification_group: :it_diploma,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            enic_notes: 'istituto tecnico diploma',
            equivalence_type: 'vocational_level_3',
            grades: ['ottimo', 'distinto', 'buono', 'sufficiente'] },
          '5f4ee000-66b3-4544-845e-94ba435e74a9' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'istituto tecnico superiore (its) – diploma di tecnico superiore',
            qualification_group: :its_diploma,
            enic_band: 'band 7–8',
            rqf_level: 'level_4–5',
            enic_notes: 'its diplomas typically eqf 5',
            equivalence_type: 'vocational_level_5',
            grades: ['ottimo', 'buono', 'sufficiente'] },
          'fa804425-c8bf-4dd0-8d07-b6aac7438983' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'laurea (bachelor\'s degree)',
            qualification_group: :degree,
            enic_band: 'band 10',
            rqf_level: 'level_6',
            equivalence_type: 'degree',
            grades: ['109/110', '91/110', '66/110 (pass)', '92/110', '99/110', '110/110 e lode', '66/110', '100/110'] },
          'dd23da24-5dd4-4c7c-b7ee-56a69740a575' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'laurea magistrale (master\'s degree)',
            qualification_group: :degree,
            enic_band: 'band 11',
            rqf_level: 'level_7',
            equivalence_type: 'degree',
            grades: ['99/110', 'awarded', '100/110', '109/110', '110/110 e lode', '66/110'] },
          '512f8f8c-d666-468f-86c2-c3923c2a947c' =>
          { country: 'italy',
            country_code: 'it',
            qualification_name: 'licenza media / esame di terza media',
            qualification_group: :licenza_media,
            enic_band: 'band 2',
            rqf_level: 'level_1–2',
            enic_notes: 'lower secondary completion',
            equivalence_type: 'gcse',
            grades: ['sufficiente', 'non sufficiente', 'distinto', 'ottimo', 'buono'],
            gcse_equivalent_grades: ['sufficiente', 'distinto', 'ottimo', 'buono'] },
          'f7b86bd2-7c75-46d6-b0ae-6e8b30e6e286' =>
          { country: 'kenya',
            country_code: 'ke',
            qualification_name: 'bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['third class', 'first class', 'second class upper', 'second class lower', 'pass'] },
          '11837aff-9c34-4b0a-995d-3dd445a81c69' =>
          { country: 'kenya',
            country_code: 'ke',
            qualification_name: 'doctorate',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '48a62ee4-41eb-4e2b-8066-45dd89c051a1' =>
          { country: 'kenya',
            country_code: 'ke',
            qualification_name: 'kenya certificate of secondary education (kcse)',
            qualification_group: :kcse,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            equivalence_type: 'gcse',
            grades: ['c-', 'b-', 'e', 'a', 'b', 'a-', 'd+', 'c+', 'c', 'd', 'd-', 'b+'],
            gcse_equivalent_grades: ['c-', 'b-', 'a', 'b', 'a-', 'c+', 'c', 'b+'] },
          '642970f4-9ac5-486d-9beb-bd8c47ead259' =>
          { country: 'kenya',
            country_code: 'ke',
            qualification_name: 'master\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['awarded', 'merit', 'pass', 'distinction'] },
          '209ec88d-d300-4496-bde7-49b3c4df42b3' =>
          { country: 'kenya',
            country_code: 'ke',
            qualification_name: 'technical and vocational education and training (tvet) diploma',
            qualification_group: :tvet,
            enic_band: 'band 6–7',
            rqf_level: 'level_3–4',
            enic_notes: 'institution-dependent',
            equivalence_type: 'a_level',
            grades: ['pass', 'credit', 'distinction'],
            gcse_equivalent_grades: ['pass', 'credit', 'distinction'] },
          '4a6635b2-6185-4df2-bfcb-cc144f8a3129' =>
          { country: 'n/a',
            country_code: 'n/a',
            qualification_name: 'international baccalaureate',
            qualification_group: :international_baccalaureate,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            equivalence_type: 'a_level',
            grades: ['good', 'satisfactory', 'mediocre', 'very_good', 'poor', 'very_poor', 'excellent'],
            gcse_equivalent_grades: ['good', 'satisfactory', 'very_good', 'excellent'] },
          '923656ce-4f23-4af3-8700-5fcb04c789a4' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'bachelor degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['gpa 2.40', '1.99', 'gpa 1.50', 'gpa 2.00', '3.49', '3.59', 'gpa 3.60', '4.49', '5', 'gpa 3.50', 'gpa 4.50', 'gpa 3.00', 'gpa 1.00', '4', '2.99', '1.49', '2.39'] },
          'fc80c00b-c707-48c7-a0d8-b40ae1c1d986' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['third class', 'second class upper', 'second class lower', 'pass', 'first class'] },
          '362488df-f505-4dce-aa3e-54dcde89dbc3' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'doctorate',
            qualification_group: :"",
            equivalence_type: 'degree',
            grades: ['awarded'] },
          'b5af6cdb-0873-4a49-8d54-171861ba9138' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'higher national diploma (hnd)',
            qualification_group: :diploma,
            enic_band: 'band 8',
            rqf_level: 'level_5',
            equivalence_type: 'diploma',
            grades: ['distinction', 'lower credit', 'upper credit'] },
          'e96d8dbb-9287-457a-bdaa-243363a087a9' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'junior secondary school certificate (jssc)',
            qualification_group: :jssc,
            equivalence_type: 'less_that_gcse',
            grades: ['a1', 'e8', 'c6', 'b2', 'd7', 'b3', 'f9'] },
          '5d138851-6947-4f2e-8ede-3c7841aa1cf4' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'master\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['pass', 'distinction', 'awarded', 'merit'] },
          'e8c5e267-33fc-49fa-ab74-1c2c82cdd2ff' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'national diploma (nd)',
            qualification_group: :diploma,
            enic_band: 'band 7',
            rqf_level: 'level_4',
            equivalence_type: 'diploma',
            grades: ['lower credit', 'distinction', 'upper credit'] },
          '86dc46d7-3a82-4c9c-a709-e6826c491ef8' =>
          { country: 'nigeria',
            country_code: 'ng',
            qualification_name: 'west african senior school certificate examination (wassce)',
            qualification_group: :wassce,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            enic_notes: 'subject-by-subject passes.',
            equivalence_type: 'gcse',
            grades: ['c5', 'a1', 'b3', 'c4', 'd7', 'b2', 'e8', 'c6'],
            gcse_equivalent_grades: ['c5', 'a1', 'b3', 'c4', 'b2', 'c6'] },
          'aebcad45-cecb-4fbe-aab0-108e9e98ffd7' =>
          { country: 'pakistan',
            country_code: 'pk',
            qualification_name: 'bachelor\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['second class lower', 'second class upper', 'third class', 'pass', 'first class'] },
          '92560123-23af-4d6c-b1d8-67e0623f43b6' =>
          { country: 'pakistan',
            country_code: 'pk',
            qualification_name: 'doctorate',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['awarded'] },
          '5a457135-be8e-40e1-a6b4-5d5eb8d64e58' =>
          { country: 'pakistan',
            country_code: 'pk',
            qualification_name: 'higher secondary school certificate (hssc)',
            qualification_group: :hssc,
            enic_band: 'band 5 (from 2026) / band 3 (pre-2026)',
            rqf_level: 'level_3_(as)_/_level_2',
            equivalence_type: 'a_level',
            grades: ['70', '50', '90', '80', '75', 'a+', 'b+', 'd', '40', 'c+', 'a1', 'a', '60', 'b', 'b++', 'a++', 'c', 'e', '95', '85'],
            gcse_equivalent_grades: ['70', '50', '90', '80', '75', 'a+', 'b+', 'c+', 'a1', 'a', '60', 'b', 'b++', 'a++', 'c', '95', '85'] },
          'e14039c5-64e9-4b39-a2eb-6bc9726edfa9' =>
          { country: 'pakistan',
            country_code: 'pk',
            qualification_name: 'master\'s degree',
            qualification_group: :degree,
            equivalence_type: 'degree',
            grades: ['merit', 'awarded', 'distinction', 'pass'] },
          '5cb7c46f-523b-46b5-a243-0c12debcbba7' =>
          { country: 'pakistan',
            country_code: 'pk',
            qualification_name: 'secondary school certificate (ssc)',
            qualification_group: :ssc,
            enic_band: 'band 3',
            rqf_level: 'level_2',
            equivalence_type: 'gcse',
            grades: ['b', '70', 'd', 'b+', '40', 'a', 'a1', 'b++', '60', '50', 'c+', 'a+', 'e', '85', '95', 'f', '75', '80', 'c', 'a++', '90'],
            gcse_equivalent_grades: ['b', '70', 'b+', 'a', 'a1', 'b++', '60', '50', 'c+', 'a+', '85', '95', '75', '80', 'c', 'a++', '90'] },
          '4717e442-8bae-4928-add7-234209d10988' =>
          { country: 'pakistan',
            country_code: 'pk',
            qualification_name: 'technical board diploma',
            qualification_group: :technical_diploma,
            equivalence_type: 'a_level',
            grades: ['a1', 'a', 'b', 'c'],
            gcse_equivalent_grades: ['a1', 'a', 'b', 'c'] },
          'f2392423-450b-4fe7-93c7-535064f10809' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'bachillerato',
            qualification_group: :bachillerato,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            enic_notes: 'university entry',
            equivalence_type: 'a_level',
            grades: ['notable', 'sobresaliente', 'suspenso', 'insuficiente', 'bien', 'suficiente', 'aprobado'],
            gcse_equivalent_grades: ['notable', 'sobresaliente', 'bien'] },
          'b7573892-4e74-474e-8165-98251362976b' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'doctorado',
            qualification_group: :degree,
            enic_band: 'band 15',
            rqf_level: 'level_8',
            equivalence_type: 'degree',
            grades: ['apto'] },
          'e06b380b-18bc-4cfb-8299-993226fc537f' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'educación secundaria obligatoria (eso)',
            qualification_group: :eso,
            enic_band: 'band 2',
            rqf_level: 'level_1–2',
            enic_notes: 'compulsory secondary',
            equivalence_type: 'gcse',
            grades: ['sobresaliente', 'suspenso', 'notable', 'insuficiente', 'aprobado', 'bien', 'suficiente'],
            gcse_equivalent_grades: ['sobresaliente', 'notable', 'bien'] },
          'f265f486-5b77-4ba2-9bb0-e6acb752d14f' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'formación profesional básica (fp básica)',
            qualification_group: :vocational_basic,
            enic_band: 'band 2',
            rqf_level: 'level_1–2',
            equivalence_type: 'btec',
            grades: ['aprobado', 'notable', 'sobresaliente'] },
          'e150f812-6e29-482a-b049-fbfe37663bdb' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'formación profesional de grado medio',
            qualification_group: :vocational_medium,
            enic_band: 'band 6',
            rqf_level: 'level_3',
            equivalence_type: 'btec',
            grades: ['aprobado', 'notable', 'sobresaliente'] },
          '1777ce42-e4ba-44b0-a776-665e56c4c021' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'formación profesional de grado superior',
            qualification_group: :vocational_top,
            enic_band: 'band 7',
            rqf_level: 'level_4',
            equivalence_type: 'btec',
            grades: ['notable', 'sobresaliente', 'aprobado'] },
          '6e5c67b9-8b16-4f31-b1d3-2272572eea92' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'grado universitario',
            qualification_group: :degree,
            enic_band: 'band 10',
            rqf_level: 'level_6',
            equivalence_type: 'degree',
            grades: ['notable', 'sobresaliente', 'aprobado'] },
          'b94f937e-75ec-4632-a81b-d45035f56a08' =>
          { country: 'spain',
            country_code: 'es',
            qualification_name: 'máster universitario',
            qualification_group: :degree,
            enic_band: 'band 11',
            rqf_level: 'level_7',
            equivalence_type: 'degree',
            grades: ['notable', 'apto', 'sobresaliente', 'aprobado'] }
        }.freeze

      DATA = DfE::ReferenceData::HardcodedReferenceList.new(
        LIST,
        schema: SCHEMA,
        list_description: 'International qualifications list',
        list_usage_guidance: 'To find an equivalent of international qualifications',
        list_docs_url: 'https://github.com/DFE-Digital/dfe-reference-data/blob/main/docs/lists_international_qualifications.md#dfereferencedatainternationalqualificationsdata',
        field_descriptions: {
          id: 'A unique identifier for this qualification record (one per country and qualification combination)',
          country: 'The country in which the qualification is awarded, lower case. `n/a` for country-agnostic qualifications such as the International Baccalaureate',
          country_code: 'The lower-case ISO 3166-1 alpha-2 code for the country (for example `cn`), or `n/a` for country-agnostic qualifications',
          qualification_name: 'The name of the qualification as awarded in that country, including any local-language title (for example `gaokao (national college entrance exam)`)',
          qualification_group: 'A symbol grouping related qualifications together (for example `:degree`, `:gaokao`, `:high_school_diploma`). Several qualification names may share a group',
          enic_band: 'The UK ENIC comparability band (for example `band 6`). A range (`band 6–7`) or dated note (`band 5 (from 2026) / band 3 (pre-2026)`) is given where ENIC provides one. Absent when ENIC has not banded the qualification',
          rqf_level: 'The comparable Regulated Qualifications Framework level, tokenised with underscores (for example `level_3`, `level_3–4`). Absent when no RQF level applies',
          enic_notes: 'A short free-text note from ENIC giving context for the comparison (for example `university entry`, `programme-dependent`). Absent when there is no note',
          equivalence_type: 'The type of UK qualification this one is broadly equivalent to (for example `a_level`, `degree`, `gcse`, `vocational_level_3`). Absent when no equivalence type has been assigned',
          grades: 'Every grade that can be awarded for this qualification, in the source country\'s own terms (for example `good`, `pass`, `a1`, or numeric marks). Order is not significant',
          gcse_equivalent_grades: 'The subset of `grades` whose ENIC GCSE-equivalence assessment is "met". Empty when no grade meets the bar, or where GCSE equivalence does not apply (for example degree-level qualifications)'
        }
      )
    end
  end
end
