require_relative 'reference_data/record'
require_relative 'reference_data/reference_list'
require_relative 'reference_data/hardcoded_reference_list'
require_relative 'reference_data/tweaked_reference_list'
require_relative 'reference_data/joined_reference_list'
require_relative 'reference_data/degrees'
require_relative 'reference_data/qualifications'
require_relative 'reference_data/itt'
