name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true
    - name: Run linters with autofix
      run: bundle exec rubocop --auto-correct-all
    - name: Push any fixes
      run: |
        git config --global user.email "lint-bot"
        git config --global user.name "lint-bot"
        git add --all
        git commit -m "Code style fixes" || exit 0
        git push
    - name: Re-run linter
      run: bundle exec rubocop
